name: Publish Release

on:
  push:
    tags:
      - 'v0.1.*'

jobs:

  unit_test_canopy:
    if: >-
      github.repository_owner == 'Cargill'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Unit Test Canopy
        run: docker-compose -f tests/test-splinter.yaml up --abort-on-container-exit unit-test-canopy-app

  unit_test_circuits:
    if: >-
      github.repository_owner == 'Cargill'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Unit Test Circuits Sapling
        run: docker-compose -f tests/test-splinter.yaml up --abort-on-container-exit unit-test-circuits-sapling

  publish_docker:
    needs: [unit_test_canopy, unit_test_circuits]
    if: >-
      github.repository_owner == 'Cargill'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish release to dockerhub
        run: ./ci/publish-docker
        env:
          NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}/
          VERSION: AUTO_STRICT
          CARGO_TERM_COLOR: always
